version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql_docker
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - mysqlvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aluraflix
    ports: 
      - 3306:3306
  adminer:
    image: adminer
    container_name: myadminer
    restart: always
    ports:
      - 8085:8080    
volumes:
  mysqlvol: